pipeline {
    agent any

    stages {

        stage('Branch Info') {
            steps {
                echo "Branch Name: ${env.BRANCH_NAME}"
            }
        }

        stage('Build') {
            steps {
                echo 'Running Build!!'
            }
        }

        stage('Test') {
            steps {
                echo 'Running Tests!!'
            }
        }

        stage('Deploy Production') {
            when {
                branch 'master'
            }
            steps {
                echo 'Deploying to Production!!'
            }
        }
    }

    post {
        always {
            echo "Pipeline completed for ${env.BRANCH_NAME}"
        }
    }
}
